### ISSUE TITLE
Only give user n seconds to answer question

### ISSUE THREAD

**Issue by kanerogers** [forginater/quiz-app#11]
## Background
Now let's make it interesting. The user has to answer the question in a limited number of seconds, or else.

## TODO
- [ ] Start with a hardcoded limit of 10 seconds
- [ ] Display the number of seconds left
- [ ] Have the number of seconds left get updated
- [ ] When the timer hits zero, tell the user they ran out of time
- [ ] Allow the user to set a custom time duration

**Comment by forginater** [comment]
## Update

Hey, mangosteen. I got a buggy as fuck version of issue11 implemented.... (Emergent issues) are outlined above which I'm working through atm. 

Based on the specifications, there are a few ways I could implement the control flow. 
- Whether user has multiple attempts at a question before time elapses or can only click "Check Answer" once.
- Once time has elapsed and outcome (Incorrect or Correct) has been displayed, can they keep guessing despite having Incorrect recorded in total score.

## Proposed Program Logic
- done = answerChecked || timeUp
- if (done) => run timer & render guessfield
- else         => display result, stop timer & freeze guessfield (maintain visible but can't change input field)

**Comment by forginater** [comment]
I chose to store "timeUp" & "answerChecked" in the local variable "done" as they have the same boolean logic with respect to the quiz control flow. 
From what I read online, with data entirely derived from state, just store it in a local variable.  I figured there are other modes and ways this could be configured where the logic of "timeUp" and "answerChecked" may diverge.
Not sure if this is the best way to do things!?

You mentioned using naive solutions: So I just wrote an extra component \<CountDownFrozen\> rather than passing in a onChange={doNothing} function to the preexisting \<GuessFrozen\> when (done is true). Using one component for the input field and using multiple onChange() functions for different scenarios passed in through props seems more elegant and uses less lines of code but I was tired and being lazy with typescript. Lemme know if this is a bad habit to adopt though.
