### ISSUE TITLE
Ask the user a series of questions

### ISSUE THREAD

**Issue by kanerogers** [forginater/quiz-app#12]
## Background
After #11 is implemented, we can then ask the user multiple questions in sequence.

## TODO
- [ ] Start with a hardcoded 10 questions
- [ ] Display the user's progress (eg. x / 10 questions)
- [ ] Once the user answers a question successfully, or the timer has elapsed, ask the next one
- [ ] If they got all the questions right, display the results
- [ ] Allow user to modify the number of questions asked
