### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by forginater** [forginater/quiz-app#13]
###TODO
---

- [ ] insert spaces between destructured variables
- [ ] See if can cleanup default empty value to avoid all the typescript shizz in the type signatures with <number | undefined> etc
- [ ] Change the name of <Answer /> to <Guess /> as it more intuitively corresponds to state names

###Possible issue to keep in mind
---
- After clicking submit once if user changes the value in the <Guess> field it immediately updates the answer "Correct" or "Incorrect" rendering the <AnswerButton> redundant... But probably will be irrelevant when introducing multiple questions in issue #12. 
- Also it will be annoying having to click the button each time if the questions are very quick, in which case will probably make sense to connect the answer submission to a particular keystroke
